---

- name: OpenSearch Install | Download opensearch {{ os_version }}
  ansible.builtin.get_url:
    url: "{{ os_download_url }}/{{ os_version }}/opensearch-{{ os_version }}-linux-x64.tar.gz"
    dest: "/tmp/opensearch.tar.gz"

- name: OpenSearch Install | Extract the tar file
  ansible.builtin.unarchive:
    src: "/tmp/opensearch.tar.gz"
    dest: "{{ os_home }}"
    extra_opts:
      - "--strip-components=1"
    remote_src: true

- name: OpenSearch Install | Copy Configuration File
  ansible.builtin.blockinfile:
    block: "{{ lookup('template', 'templates/opensearch-{{ cluster_type }}.yml') }}"
    dest: "{{ os_conf_dir }}/opensearch.yml"
    state: present
    create: true
    marker: "## {mark} opensearch main configuration ##"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0755

- name: OpenSearch Install | Copy jvm.options File for Instance
  ansible.builtin.template:
    src: jvm.options
    dest: "{{ os_conf_dir }}/jvm.options"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0755
    force: true

- name: OpenSearch Install | create systemd service
  ansible.builtin.template:
    src: opensearch.service
    dest: "{{ systemctl_path }}/opensearch.service"
